### ISSUE TITLE
hoho no list 

### ISSUE THREAD

**Issue by buzzdeee** [CounterHack/HolidayHack2021#2]
I had 91 IPs on the naughtylist, reading discord, obviously too many.

so I ran:

`fail2ban-client unban --all`

and the end of the output of the command:

```
...
218.229.229.128 has been removed from the naughty list!
146.205.232.59 has been removed from the naughty list!
163.103.52.58 has been removed from the naughty list!
You correctly identifed 15 IPs out of 15 bad IPs
You incorrectly added 0 benign IPs to the naughty list

*******************************************************************
* You stopped the attacking systems! You saved our systems!
*
* Thank you for all of your help. You are a talented defender!
*******************************************************************
91
```

not sure if that is/was intended?

anyways, thanks for the fun ;)

**Comment by joswr1ght** [comment]
Thank you for the note! We're looking into it!

**Comment by joswr1ght** [comment]
Thanks again for the report @buzzdeee! I spent some time looking into this, as did Andy Smith, the amazing challenge designer of Ho Ho ... No. We both concur that this was a bit of a fluke, where the background task that verifies completion of the challenge wrote to the terminal TTY in the middle of a line, causing the strange trailing `91`.

Neither Andy nor I could reproduce this behavior, and I don't believe that it takes away substantially from the challenge itself. I'm going to close this issue, but feel free to reopen if you experience this issue again!

Thank you! Our HHC players are the best. 🙌
