### ISSUE TITLE
#12 Frost Tower Website - Contact form error

### ISSUE THREAD

**Issue by Nodeblue** [CounterHack/HolidayHack2021#3]
When performing a basic form submission at https://staging.jackfrosttower.com/contact you receive a 500 error: Internal Server Error.

I believe this is an issue.

**Comment by Nodeblue** [comment]
Looks like it is back up again. Now working.

**Comment by edskoudis** [comment]
That’s good news. Sorry for the interruption of services. Thanks for letting us know. 

Happy holidays!!!

--Ed.
